targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          generic_argument_factories: false
          include_if_null: false

